import { type NextPage } from "next"
import Head from "next/head"
import NextLink from "next/link"
import { signIn, signOut, useSession } from "next-auth/react"

import { api } from "@/utils/api"
import RootLayout from "@/layouts/root-layout"
import { Box, Button, Text } from "@chakra-ui/react"

const Home: NextPage = () => {
	const { data: sessionData } = useSession()

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<RootLayout>
				<Box>
					<Button onClick={sessionData ? () => void signOut() : () => void signIn()}>
						{sessionData ? "Sign out" : "Sign in"}
					</Button>
				</Box>
			</RootLayout>
		</>
	)
}

export default Home
