import SignUpForm from "@/components/auth/sign-up-form"
import CleanLayout from "@/layouts/clean-layout"
import { Flex, Stack, Heading, Text, Link, useBreakpointValue } from "@chakra-ui/react"
import Head from "next/head"
import NextLink from "next/link"

const SignUp = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CleanLayout>
				<Flex minH={"100vh"} align={"center"} justify={"center"}>
					<Stack
						spacing={8}
						mx={"auto"}
						minW={useBreakpointValue({ base: "auto", sm: "md" })}
						maxW={"lg"}
						py={12}
					>
						<Stack align={"center"}>
							<Heading fontSize={"4xl"}>Create an Account</Heading>
							<Text>
								Already have an account{" "}
								<Link as={NextLink} href="/sign-in" color="blue.400">
									Login
								</Link>
							</Text>
						</Stack>
						<SignUpForm />
					</Stack>
				</Flex>
			</CleanLayout>
		</>
	)
}

export default SignUp
